development:
  adapter: mysql2
  encoding: utf8
  database: SparkGather_development
  pool: 5
  username:
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: SparkGather_test
  pool: 5
  username:
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: SparkGather_production
  pool: 5
  username:
  password:
